version: '3'
services:
  envoy:
   image: envoyproxy/envoy:v1.23-latest
   container_name: envoy
   network_mode: host
   volumes:
    - /root/envoy/config:/config
   command: envoy -c /config/envoy-demo.yaml -l trace

# --log-path /config/custom.log 配置日志路径

     
   
